// Pin the style definitions locally; tiles, fonts and sprites remain on OpenFreeMap.
// Upstream styles: https://openfreemap.org/quick_start/ (OpenMapTiles BSD styles).
import fs from 'node:fs';
const definitions = await Promise.all(['positron', 'dark'].map(async name => {
  const response = await fetch(`https://tiles.openfreemap.org/styles/${name}`);
  if (!response.ok) throw new Error(`Style ${name}: HTTP ${response.status}`);
  return response.json();
}));
const [light, dark] = definitions;
if (light.sprite !== dark.sprite || light.glyphs !== dark.glyphs) throw new Error('Basemap assets differ');
// The upstream dark style uses very faint place names. Keep them readable.
for (const layer of dark.layers) if (layer.type === 'symbol' && layer.layout?.['text-field']) {
  layer.paint = {...layer.paint, 'text-color':'#b8c7d6', 'text-halo-color':'#18212a', 'text-halo-width':1.3};
}
const layers = definitions.flatMap((style, i) => style.layers.map(layer => ({
  ...layer, id: `base-${i ? 'dark' : 'clean'}-${layer.id}`,
  metadata: { basemap: i ? 'dark' : 'clean', originalVisibility: layer.layout?.visibility || 'visible' },
  layout: { ...layer.layout, visibility: i ? 'none' : (layer.layout?.visibility || 'visible') },
})));
const style = { version: 8, glyphs: light.glyphs, sprite: light.sprite, sources: light.sources,
  layers: [...layers.filter(l => l.type !== 'symbol'), ...layers.filter(l => l.type === 'symbol')] };
style.sources.openmaptiles.attribution = '<a href="https://openfreemap.org/">OpenFreeMap</a> · <a href="https://openmaptiles.org/">OpenMapTiles</a> · <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>';
fs.writeFileSync('basemaps.js', '// OpenFreeMap Positron and Dark styles; generated by build_basemaps.mjs.\nconst FREE_BASE_STYLE=' + JSON.stringify(style) + ';\n');
console.log(`Saved ${layers.length} basemap layers without API keys.`);
